### ISSUE TITLE
Use the new API URLs and deprecate the old endpoints

### ISSUE THREAD

**Issue by RobotSail** [sashabaranov/go-gpt3#27]
OpenAI's API has recently changed so API calls are made to endpoints such as `/v1/completions` for completions instead of `/v1/engines/${engineID}/completions`.

I'm currently migrating to using go-gpt3 instead of my own client, and would like to incorporate a mock server for simulating responses. This would be incredibly helpful to avoid handling the old API.

**Comment by galpt** [comment]
_Hi @RobotSail, are you going to update the `moderation.go` too?
If you have the time, could you please also handle that one too?
So that it can be merged into only 1 pull request.
If you don't really have the opportunity , it's okay, I can update it later after your pull request got approved. :)_

_I got an email from OpenAI this morning about the changes they made:_

Hi there,

Thanks for being a user of OpenAI’s [moderations](http://url3243.email.openai.com/ls/click?upn=8NGuCp9HhBmIwvt7K-2Bq2nAJwR-2FiGg6tWLLCR-2FMAr5DAqJWti5qq8wK9SQWsFusD41AqRaDPkpfRd-2F-2BsuhGmj0Q-3D-3DW_YD_2RTcX7-2BP6xX4BlkOEEGhfOBSbUx-2FSe4q-2BCFmj5B1H9lBRGiAJorrlC4PlWxJUTKu9OSFCC5T6zbgcs8csHBqwUDUy0RAEVTZifFgobwh9LklZ7Ef4iy2PS8KpB-2Befx8mRMnb0uNij-2BNaodk5tpvgxcGm-2BfohFZfcnJ1kK5hLVB-2BeeM7ahgObSyBwYcsDe-2FSQsEJp0y3Efs0woELYKK9rEIQUV0qKyUYb2SS1zJWbv2kIGV5e8fv32Isp5NDTL9di-2Bz01pelS9xQSnycs8GMIohO4Td-2BMENfOhvvBSgrKsAthRtTh9E-2BzAsvMZ3n76HL5rqBRQf1lMrExxrxOCGOHFrxeb0iRpWhlejBELNggFdAUTNSdeDIxHTzFUNFVmPyMAM3mVnImWdEkKS68kzjgQKLjJSpVZWunanu7FHql5-2FP0Pb6V6oSJLkJKuUhpep3Mfi2eZusRx8DCOaA3bY3EgFElvqhhWYhNcPuXVk1sBj3BYQfskJ34nUDE85FlTuZms9OBS-2FsUDhe2jNEBssRl2gYQ3Cacrbj9FPD4KH2SnKOBJQCg1JAmPFly0czIvwkd7aa5dqxAfFdflHgrgKculG4CJ9pBb-2B0qVHSPtlJ4AtVzNi3WR80-2FHd1aO9o4bgu167YkiEZMARfRWJR56Gyd8zzj7QHlXXSEjv3ljV6UtJh6iLyB6IFYp-2FSZVrP4gbDtBK5-2BLUAagWjKOVAazlkbOQ7WwYGcHXm6Z9IrxQjJ8iDuvc8I2RP-2BuxbAgomaphrwl3mc9KmPpYeTSygWgL8jn4CcyZ1UCnWngYKAGxNPsCWjZm4iF6TPpubIZl1dgesJFuqEUbMZNZIbcodqeSeuvcbzxGQEJA0P5g38Rs9xVw-2B4gP4otRFg0WVwl2KVjLwws2LvMGvmd7VSjuLvDcAXFu-2BKsVYPer2E69pMs-2Bmbw-2FM65c7F63nKJaw5R2Q-2BOTgb) endpoint!

I’m writing to inform you about the following breaking change in our API.

Starting Friday, August 5th 2022, the type of moderation endpoint response fields `flagged` and each field in `categories` will change from Integer to Boolean. Return values of `1` will now be `true` and return values of `0` will be `false`. Below is an example output of the updated endpoint.

If your application relies on these fields being integers, please update your code to rely on booleans. Otherwise no action is required on your end.

Please reach out to [support@openai.com](mailto:support@openai.com?subject=Re:+Moderation+API+breaking+change&body=) if you have any concerns with this change. Thanks!
```
{
  "id": "modr-XXXXX",
  "model": "text-moderation-001",
  "results": [
    {
      "categories": {
        "hate": false,
        "hate/threatening": false,
        "self-harm": false,
        "sexual": false,
        "sexual/minors": false,
        "violence": false,
        "violence/graphic": false
      },
      "category_scores": {
        "hate": 0.18805529177188873,
        "hate/threatening": 0.0001250059431185946,
        "self-harm": 0.0003706029092427343,
        "sexual": 0.0008735615410842001,
        "sexual/minors": 0.0007470346172340214,
        "violence": 0.0041268812492489815,
        "violence/graphic": 0.00023186142789199948
      },
      "flagged": false
    }
  ]
}
```
Best,
Angela

**Comment by sashabaranov** [comment]
@RobotSail thank you for the PR! 🙌🏻  The mock server is also really welcome here. Previously this repo was declined from the awesome-go list due to a lack of mock server testing.
